### ISSUE TITLE
non-REST-API way broken?

### ISSUE THREAD

**Issue by dvzrv** [owncloud/news-updater#2]
I'm having troubles getting the non-REST-API way (direct call to occ script) to run.
The script throws exit code 1 and thus news-updater won't work.

If I call this myself, it doesn't work either:

```
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /usr/share/webapps/owncloud/lib/private/db/connection.php:54

```

I'm trying to setup the systemd service for it, but so far not with too much luck.
Using the REST-API way doesn't break.

I'm suspecting a possible packaing problem with Arch Linux.
Maybe someone has had a similar issue?

**Comment by BernhardPosselt** [comment]
You probably did not enable the proper database extensions for your CLI. Some distros use different php.inis

**Comment by dvzrv** [comment]
@BernhardPosselt: ah... that put me up on the right track!!
I have ALL extensions globally disabled and only allow some of them, depending on the webapp's needs using uwsgi settings.
Thanks for the hint!
Calling
`sudo -u http php -c /path/to/my/special/php.ini occ
`
solved it for me!

**Comment by BernhardPosselt** [comment]
Sorry for the delay btw, forgot to turn on github notifications ;D
